/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author chitr
 */
public class OfficerLogin extends javax.swing.JFrame {

    /**
     * Creates new form OfficerLogin
     */
    public OfficerLogin() {
        initComponents();
    }
    private String dburl = "jdbc:mysql://localhost:3306/loginportal";
    private String uid = "root";
    private String pwd = "root";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        playerSwitchButton = new javax.swing.JButton();
        playerTabbedPane = new javax.swing.JTabbedPane();
        playerPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        emailLoginLabel = new javax.swing.JLabel();
        emailLoginTextField = new javax.swing.JTextField();
        passwordLoginLabel = new javax.swing.JLabel();
        loginPlayerButton = new javax.swing.JButton();
        loginPasswordField = new javax.swing.JPasswordField();
        registerScrollPane = new javax.swing.JScrollPane();
        registerPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        emailRegisterLabel = new javax.swing.JLabel();
        emailRegisterTextField = new javax.swing.JTextField();
        passwordRegisterLabel = new javax.swing.JLabel();
        registerPasswordField = new javax.swing.JPasswordField();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(823, 465));

        headerPanel.setBackground(java.awt.Color.black);

        headerLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        headerLabel.setForeground(java.awt.Color.white);
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Portal - Officer's Login");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addGap(39, 39, 39))
        );

        footerPanel.setBackground(java.awt.Color.black);

        playerSwitchButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        playerSwitchButton.setText("Player");
        playerSwitchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerSwitchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playerSwitchButton)
                .addContainerGap())
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerSwitchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        playerTabbedPane.setBackground(java.awt.Color.white);
        playerTabbedPane.setPreferredSize(new java.awt.Dimension(826, 504));
        playerTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerTabbedPaneMouseClicked(evt);
            }
        });

        playerPanel.setBackground(java.awt.Color.white);

        loginPanel.setBackground(java.awt.Color.white);

        emailLoginLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailLoginLabel.setText("Enter Email");

        passwordLoginLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passwordLoginLabel.setText("Enter Password");

        loginPlayerButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginPlayerButton.setText("LOGIN");
        loginPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPlayerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginPlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(emailLoginLabel)
                    .addComponent(passwordLoginLabel)
                    .addComponent(loginPasswordField)
                    .addComponent(emailLoginTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(emailLoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(passwordLoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(loginPlayerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout playerPanelLayout = new javax.swing.GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        playerPanelLayout.setVerticalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        playerTabbedPane.addTab("Login", playerPanel);

        registerScrollPane.setBorder(null);
        registerScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        registerScrollPane.setAutoscrolls(true);

        registerPanel.setBackground(java.awt.Color.white);

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        firstNameLabel.setText("First Name");

        firstNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lastNameLabel.setText("Last Name");

        lastNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        emailRegisterLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailRegisterLabel.setText("Enter Email");

        emailRegisterTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        passwordRegisterLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passwordRegisterLabel.setText("Enter Password");

        registerPasswordField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phoneLabel.setText("Enter Phone No");

        phoneTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        registerButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneLabel)
                    .addComponent(passwordRegisterLabel)
                    .addComponent(emailRegisterLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(lastNameTextField)
                    .addComponent(emailRegisterTextField)
                    .addComponent(registerPasswordField)
                    .addComponent(phoneTextField)
                    .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(firstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lastNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailRegisterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailRegisterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordRegisterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        registerScrollPane.setViewportView(registerPanel);

        playerTabbedPane.addTab("Register", registerScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playerTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPlayerButtonActionPerformed
        // TODO add your handling code here:
        String email = emailLoginTextField.getText();
        String password = loginPasswordField.getText();
        String query = "select pass from officer where email = '"+email+"'";
        try{
            Connection con = (Connection)DriverManager.getConnection(dburl, uid,pwd);
            Statement stmt = (Statement)con.createStatement();
            ResultSet rset = stmt.executeQuery(query);
            while(rset.next()){
                if(password.equals(rset.getString("pass"))){
                    new OfficerList(email).setVisible(true);
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Incorrect email or password");
                }
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_loginPlayerButtonActionPerformed

    private void playerTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerTabbedPaneMouseClicked
        // TODO add your handling code here:
        String name = playerTabbedPane.getSelectedComponent().toString();
        System.out.println(name);
    }//GEN-LAST:event_playerTabbedPaneMouseClicked

    private void playerSwitchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerSwitchButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PlayerLogin().setVisible(true);
    }//GEN-LAST:event_playerSwitchButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        String fname = firstNameTextField.getText();
        String lname = lastNameTextField.getText();        
        String email = emailLoginTextField.getText();
        String password = loginPasswordField.getText();
        int phone = Integer.parseInt(phoneTextField.getText());
        String query = "insert into officer values('"+fname+"','"+lname+"','"+email+"','"+password+"',"+phone+"')";
        try{
            Connection con = (Connection)DriverManager.getConnection(dburl, uid,pwd);
            Statement stmt = (Statement)con.createStatement();
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Officer registered Successfully");
            new OfficerList(email).setVisible(true);
            this.setVisible(false);
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfficerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLoginLabel;
    private javax.swing.JTextField emailLoginTextField;
    private javax.swing.JLabel emailRegisterLabel;
    private javax.swing.JTextField emailRegisterTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JButton loginPlayerButton;
    private javax.swing.JLabel passwordLoginLabel;
    private javax.swing.JLabel passwordRegisterLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JButton playerSwitchButton;
    private javax.swing.JTabbedPane playerTabbedPane;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPasswordField registerPasswordField;
    private javax.swing.JScrollPane registerScrollPane;
    // End of variables declaration//GEN-END:variables
}
